export const DEFAULT_MIN_THRESHOLD = 0;
export const DEFAULT_MAX_THRESHOLD = 100;
export const DEFAULT_PREFIX = '[';
export const DEFAUT_DELIMITER = 'TO';
export const DEFAULT_SUFFIX = ']';

export const DEFAULT_MIN_VALUE = DEFAULT_MIN_THRESHOLD;
export const DEFAULT_MAX_VALUE = DEFAULT_MAX_THRESHOLD;
